[package]
description = "A library to provide error decorator with the location and the source of the original error."
keywords = ["errors", "helper", "library"]
name = "located-error"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log = { version = "0", features = ["release_max_level_info"] }

[dev-dependencies]
thiserror = "1.0"
