log_level = "info"

[website]
name = "Warehouse Management Development"

[net]
ip = "127.0.0.1"
port = 6000
# localhost and * are special mark
v4 = "localhost"
v4port = 6000
v6 = "localhost"
v6port = 6000
stream_sock = "/run/wm_stream.sock"
datagram_sock = "/run/wm_datagram.sock"

[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"

[database]
connect_url = "sqlite://storage/database/wm.sqlite?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
username = ""
password = ""
server = ""
port = 25

[image_cache]
max_request_timeout_ms = 1000
capacity = 128000000
entry_size_limit = 4000000
user_quota_period_seconds = 3600
user_quota_bytes = 64000000

[api]
default_page_size = 10
max_page_size = 30
